### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [gaveinti/ISII-WORKSHOPS-SEPROAMERICA#4]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by gaveinti** [comment]
Dear customer, we have read your request and we are going to work on it.

**Comment by gaveinti** [comment]
We've proceeded to categorize this issue as "Analysing the issue"

**Comment by gaveinti** [comment]
We will proceed to process the request, me @gaveinti  will be the assigned analyst and @BryanLoor will develop the solution and will perform the tests.

**Comment by gaveinti** [comment]
Dear customer, here is the impact analysis report. Please tell us if you agree. Thank you
[Impact analysis.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10462923/Impact.analysis.docx)

**Comment by pmaldonado-espol** [comment]
> Dear customer, here is the impact analysis report. Please tell us if you agree. Thank you
> [Impact analysis.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10462923/Impact.analysis.docx)

It’s Okay, go ahead.

**Comment by gaveinti** [comment]
https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/blob/dd84db081d323d95e1eb7083b2f90210cf23b467/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Cliente.java#L52-L78

**Comment by gaveinti** [comment]
Here we attach the test
[Test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468640/Test.plan.docx)
 plan with its results

**Comment by gaveinti** [comment]
Here we attach the test plan with its results. 
[Test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468641/Test.plan.docx)

**Comment by gaveinti** [comment]
Here is the acceptance test plan we've produced, @pmaldonado-espol . Please tell us if you agree with this report.
[Acceptance test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468792/Acceptance.test.plan.docx)

**Comment by pmaldonado-espol** [comment]
> Here is the acceptance test plan we've produced, @pmaldonado-espol . Please tell us if you agree with this report.
> [Acceptance test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468792/Acceptance.test.plan.docx)

The Acceptance Tests Plan must include the execution steps

**Comment by gaveinti** [comment]
Here is the acceptance test with the execution steps included @pmaldonado-espol. Please tell us if you agree to continue.
[Acceptance test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468923/Acceptance.test.plan.docx)

**Comment by pmaldonado-espol** [comment]
> Here is the acceptance test with the execution steps included @pmaldonado-espol. Please tell us if you agree to continue.
> [Acceptance test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10468923/Acceptance.test.plan.docx)

It’s OK.

**Comment by gaveinti** [comment]
Good afternoon customer, please tells us if you agree with the last acceptance test sent so we can continue. Thank you for your time. @pmaldonado-espol 
[Acceptance test plan.docx](https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA/files/10470580/Acceptance.test.plan.docx)

**Comment by gaveinti** [comment]
Undestood. Can you execute the code in order to see if the solutiuon is correct?

**Comment by gaveinti** [comment]
The solution has been completed and the programmer @BryanLoor will release the new software version for you @pmaldonado-espol

**Comment by gaveinti** [comment]
Program execution manual:
1. Clone the repository in your machine using the command above: 
git clone https://github.com/gaveinti/ISII-WORKSHOPS-SEPROAMERICA.git
2. Open the program with the IDE of your preference
3. Go to the CarInsurance.java component
4. Run the program as a java application
5. Test the first case writing te next values in order: s, 31, M, Married
6. Make sure that the result value shown is 200
7. Run the program again as a java application
5. Test the second case writing te next values in order: s, 61, F, Single
8. Make sure that the result value shown is 150

@pmaldonado-espol

**Comment by gaveinti** [comment]
@pmaldonado-espol, the program execution manual is available in order to guide you through the process to test the request.
